name: "ant-vpn"
 
on:
  push:
    branches: [ $default-branch ]
  schedule:
    - cron: "29 * * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ant-vpn/requirements.txt
    - name: running
      run: python ant-vpn/index.py
